version: '3.7'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - FLASK_ENV=docker
    ports:
      - 5001:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint:
      - /app/scripts/docker_script.sh
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - ./pgadmin-volume:/var/lib/pgadmin/storage/

volumes:
  flask-app-db:
    name: flask-app-db
